<a href="https://colab.research.google.com/github/Goutham-26/DSA/blob/main/Numpy_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np

# Create a NumPy array with values from 10 to 49 (inclusive)
array = np.arange(10, 50)
print("Original array:")
print(array)

Original array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [56]:
# Reshape it into a 4x10 matrix
matrix = array.reshape(4, 10)
print("\nReshaped 4x10 matrix:")
print(matrix)


Reshaped 4x10 matrix:
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [57]:
# Extract the last column from the reshaped matrix
last_column = matrix[:, -1]
print("\nLast column of the matrix:")
print(last_column)


Last column of the matrix:
[19 29 39 49]


In [58]:
# Create two 3×3 matrices: One filled with all 5s , One with values from 1 to 9
#● Add the two matrices
#● Multiply them element-wise
#● Then find the transpose of the result

In [59]:
# Create a 3x3 matrix filled with all 5s
matrix_fives = np.full((3, 3), 5)
print("Matrix 1 (all 5s):\n", matrix_fives)

Matrix 1 (all 5s):
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [60]:
# Create a 3x3 matrix with values from 1 to 9
matrix_one_to_nine = np.arange(1, 10).reshape(3, 3)
print("\nMatrix 2 (1 to 9):\n", matrix_one_to_nine)


Matrix 2 (1 to 9):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
# Add the two matrices
matrix_sum = matrix_fives + matrix_one_to_nine
print("\nSum of the  matrices:\n", matrix_sum)


Sum of the  matrices:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [62]:
# Multiply them element-wise
matrix_product = matrix_fives * matrix_one_to_nine
print("\n product of the two matrices:\n", matrix_product)


 product of the two matrices:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [63]:
# Find the transpose of the element-wise product
matrix_product_transpose = matrix_product.T
print("\nTranspose:\n", matrix_product_transpose)


Transpose:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [64]:
# Create a NumPy array of 15 random integers between 10 and 100
random_array = np.random.randint(10, 101, 15)
print("random array:")
print(random_array)

random array:
[48 33 77 88 11 93 29 97 38 94 19 45 55 50 47]


In [65]:
#Replace all values greater than 50 with -1
greater = random_array > 50
random_array[greater] = -1
print("\nModified array:")
print(random_array)

#Count how many values were replaced.
count_replaced = np.count_nonzero(greater_than_50)
print("\nNumber of values replaced:", count_replaced)


Modified array:
[48 33 -1 -1 11 -1 29 -1 38 -1 19 45 -1 50 47]

Number of values replaced: 8


In [66]:
# Generate a 5x4 array with random values between 0 and 1 (float).
random_float_array = np.random.rand(5, 4)
print("5x4 array :\n", random_float_array)

5x4 array :
 [[0.5426118  0.68778889 0.82990007 0.89656653]
 [0.57221308 0.83757814 0.11893892 0.8529013 ]
 [0.98614812 0.26706482 0.57698274 0.15249458]
 [0.08003501 0.92511868 0.83195151 0.83988883]
 [0.02604373 0.28107859 0.71702905 0.79855938]]


In [67]:
#Find the row with the maximum sum of values.
max_sum_row = np.argmax(np.sum(random_float_array, axis=1))
print("\nRow with the maximum sum of values:", max_sum_row)


Row with the maximum sum of values: 0


In [68]:
#arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
#● Find all unique elements


In [69]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
print("Original array:", arr)

# Find all unique elements
unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)

Original array: [1 3 5 3 7 9 1 5 5]
Unique elements: [1 3 5 7 9]


In [70]:
#Find the duplicates (elements that appear more than once)
unique, counts = np.unique(arr, return_counts=True)
duplicates = unique[counts > 1]
print("Duplicates:", duplicates)

Duplicates: [1 3 5]


In [71]:
# Create a 6×6 NumPy array with values from 1 to 36.
array_36 = np.arange(1, 37).reshape(6, 6)
print("6x6 array:\n", array_36)

6x6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [72]:
#Extract the middle 4×4 submatrix.
submatrix = array_36[1:5, 1:5]
print("\n4x4 submatrix:\n", middle_submatrix)


4x4 submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [73]:
#Then extract all even numbers from this submatrix.
even_numbers = submatrix[submatrix % 2 == 0]
print("\nEven numbers from the submatrix:\n", even_numbers)


Even numbers from the submatrix:
 [ 8 10 14 16 20 22 26 28]


In [74]:
# Generate an array of shape (3, 4) with values from 0 to 11.
array1 = np.arange(12).reshape(3, 4)
print("Array of shape (3, 4) :\n", array1)

Array of shape (3, 4) :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [75]:
#Reshape it to (2, 6)
reshaped_array = array1.reshape(2,6)
reshaped_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [76]:
#Then flatten it into a 1D array
flattened_array = reshaped_array.flatten()
flattened_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
#Convert the 1D array back to shape (4, 3)
reshaped = flattened_array.reshape(4, 3)
reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
# Create an array: a = np.array([[1, 2], [3, 4]])
a = np.array([[1, 2], [3, 4]])
#Append a new row [5, 6]
new_row = np.array([5, 6])
appended_array = np.vstack((a, new_row))
appended_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
#Then append a new column [7, 8, 9]
new_column = np.array([[7], [8], [9]])
appended_array = np.hstack((appended_array, new_column))
appended_array

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [80]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
#Join them into a single array
joined_array = np.concatenate((a, b, c))
joined_array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
#Reshape the result into a 3×3 matrix
reshaped_matrix = joined_array.reshape(3, 3)
reshaped_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
#Extract the diagonal elements
diagonal_elements = np.diag(reshaped_matrix)
diagonal_elements

array([1, 5, 9])

In [83]:
#Create a NumPy array of integers from 1 to 20.
array_20 = np.arange(1, 21)
array_20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [84]:
#Extract all values that are divisible by 3 or 5.
divisible = array_20[(array_20 % 3 == 0) | (array_20 % 5 == 0)]
divisible

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20])

In [85]:
#Count how many such values exist.
count_divisible = len(divisible)
print("Number of values divisible by 3 or 5:", count_divisible)

Number of values divisible by 3 or 5: 9
